### ISSUE TITLE
Messy repo

### ISSUE THREAD

**Issue by ouked** [alex-and-the-antelopes/BillTracker#25]
We need to put files into folders with related files (i.e. email functionality).
Ideally we want the fewest files at the project root as possible.

**Comment by sg2295** [comment]
We can group:
- Notifications
- Emails

In a sub-folder called "Communication" or "Interactions", since they are used to send messages to either MPs or the Users' themselves.

**Comment by sg2295** [comment]
- [x] Need to remove old branches.
